variables:
  #########################################
  ###### Example of global variables ######
  #########################################
  # CI_REGISTRY: docker.io
  # CI_PROJECT: nginx
  # CI_REGISTRY_USER: toto
  # CI_REGISTRY_PASSWORD: tata
  #########################################
  API_VERSION: "1.8.5"
  REPOSITORY_NAME: $CI_REGISTRY/$CI_PROJECT

stages:
  - tests
  - deploy

tests:lint-secaudit:
  stage: tests
  image: ubuntu:18.04
  script:
    - chmod u+x prepare-ci-env.bash
    - . ./prepare-ci-env.bash 3.8
    - flake8 --extend-exclude=venv,migrations --ignore=E402
    - bandit -n5 -x "./venv/*,./tests/*,./dev-tools/*" -r . -ll

# TODO : Find why the api need to be in capsule-api directory

tests:python36:
  stage: tests
  image: ubuntu:18.04
  script:
    - cd ..; mv api capsule-api; cd capsule-api
    - chmod u+x prepare-ci-env.bash
    - . ./prepare-ci-env.bash 3.6
    - python -m pytest -v -n4 tests/api/

tests:python37:
  stage: tests
  image: ubuntu:18.04
  script:
    - cd ..; mv api capsule-api; cd capsule-api
    - chmod u+x prepare-ci-env.bash
    - . ./prepare-ci-env.bash 3.7
    - python -m pytest -v -n4 tests/api/

tests:python38:
  stage: tests
  image: ubuntu:18.04
  script:
    - cd ..; mv api capsule-api; cd capsule-api
    - chmod u+x prepare-ci-env.bash
    - . ./prepare-ci-env.bash 3.8
    - python -m pytest -v -n4 --cov=. --cov-config=.coveragerc-ci --cov-report html --cov-report term tests/api/

deploy:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - export TAG_VERSION=$(printf '%s-%05d' ${CI_COMMIT_SHA:0:8} ${CI_PIPELINE_ID})
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context . --destination ${REPOSITORY_NAME}/capsule-api:${API_VERSION}-${TAG_VERSION} --build-arg http_proxy=${HTTP_PROXY} --build-arg https_proxy=${HTTP_PROXY} --build-arg no_proxy=${NO_PROXY}
  only:
    - master
  when: manual
