variables:
  #########################################
  ###### Example of global variables ######
  #########################################
  # CI_REGISTRY: docker.io
  # CI_PROJECT: nginx
  # CI_REGISTRY_USER: toto
  # CI_REGISTRY_PASSWORD: tata
  #########################################
  API_VERSION: "2.2.0"
  REPOSITORY_NAME: $CI_REGISTRY/$CI_PROJECT

stages:
  - tests
  - deploy

tests:lint-secaudit:
  stage: tests
  image: harbor.in.ac-versailles.fr/library/ubuntu:22.04
  script:
    - chmod u+x prepare-ci-env.bash
    - . ./prepare-ci-env.bash 3.10
    - flake8 --extend-exclude=venv,migrations --ignore=E402
    - bandit -n5 -x "./venv/*,./tests/*,./dev-tools/*" -r . -ll
  allow_failure: true

tests:python3:
  stage: tests
  image: harbor.in.ac-versailles.fr/library/ubuntu:22.04
  script:
    - cd ..; mv api capsule-api; cd capsule-api
    - chmod u+x prepare-ci-env.bash
    - . ./prepare-ci-env.bash 3.10
    - python -m pytest -v -n4 --cov=. --cov-config=.coveragerc-ci --cov-report html --cov-report term  --disable-pytest-warnings tests/api/

deploy:dev:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - export TAG_VERSION="${CI_COMMIT_SHORT_SHA}-${CI_PIPELINE_ID}"
    - export REPOSITORY_NAME=${CI_REGISTRY}/sandbox
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context . --destination ${REPOSITORY_NAME}/capsule-api:${API_VERSION}-${TAG_VERSION} --build-arg http_proxy=${HTTP_PROXY} --build-arg https_proxy=${HTTP_PROXY} --build-arg no_proxy=${NO_PROXY}
  only:
    - branches
  except:
    - master

deploy:prod:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - export TAG_VERSION="${CI_COMMIT_SHORT_SHA}-${CI_PIPELINE_ID}"
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context . --destination ${REPOSITORY_NAME}/capsule-api:${API_VERSION}-${TAG_VERSION} --build-arg http_proxy=${HTTP_PROXY} --build-arg https_proxy=${HTTP_PROXY} --build-arg no_proxy=${NO_PROXY}
  only:
    - master
  when: manual
