variables:
  #########################################
  ###### Example of global variables ######
  #########################################
  # CI_REGISTRY: docker.io
  # CI_PROJECT: nginx
  # CI_REGISTRY_USER: toto
  # CI_REGISTRY_PASSWORD: tata
  #########################################
  API_VERSION: "1.6"
  REPOSITORY_NAME: $CI_REGISTRY/$CI_PROJECT

stages:
  - tests
  - deploy

tests:lint-secaudit:
  stage: tests
  image: ubuntu:18.04
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get update -qy
    - DEBIAN_FRONTEND=noninteractive apt-get install -y python3.6 python3-pip
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install -r requirements.txt -r test-requirements.txt
    - flake8 --extend-exclude=venv,migrations --ignore=E402
    - bandit -n5 -x "./venv/*,./tests/*,./dev-tools/*" -r . -ll

tests:python36:
  stage: tests
  image: ubuntu:18.04
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get update -qy
    - DEBIAN_FRONTEND=noninteractive apt-get install -y python3.6 python3-pip
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install -r requirements.txt -r test-requirements.txt
    - python -m pytest -v -n4 --cov=. --cov-config=.coveragerc-ci --cov-report html --cov-report term tests/api/

tests:python37:
  stage: tests
  image: ubuntu:18.04
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get update -qy
    - DEBIAN_FRONTEND=noninteractive apt-get install -y python3.7 python3-pip
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install -r requirements.txt -r test-requirements.txt
    - python -m pytest -v -n4 tests/api/

tests:python38:
  stage: tests
  image: ubuntu:18.04
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get update -qy
    - DEBIAN_FRONTEND=noninteractive apt-get install -y python3.8 python3-pip
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install -r requirements.txt -r test-requirements.txt
    - python -m pytest -v -n4 tests/api/

deploy:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - export TAG_VERSION=$(printf '%s-%05d' ${CI_COMMIT_SHA:0:8} ${CI_PIPELINE_ID})
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context . --destination ${REPOSITORY_NAME}/capsule-api:${API_VERSION}-${TAG_VERSION} --build-arg http_proxy=${HTTP_PROXY} --build-arg https_proxy=${HTTP_PROXY} --build-arg no_proxy=${NO_PROXY}
  only:
    - master
  when: manual
