dist: xenial
language: python
python:
  - "3.6"

services:
  - 'docker'

before_install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

# script:
#   - pytest -v

after_success:
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin
  - docker build -t ${DOCKER_USER}/capsule-api .
  - docker push ${DOCKER_USER}/capsule-api
