dist: bionic

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install python3.6 python3-pip
  - python3 -m pip install --upgrade tox

jobs:
  include:
    - stage: lint
      script:
        - tox -e lint
    - stage: audit
      script:
        - tox -e secaudit
    - stage: cover
      script:
        - tox -e fullcover