dist: xenial
language: python
python:
  - "3.6"

services:
  - 'docker'

before_install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - echo "hello ${{ secrets.DOCKER_USER }}"
#   - pytest -v

after_success:
  - echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USER }}" --password-stdin
  - docker build -t ${{ secrets.DOCKER_USER }}/capsule-api .
  - docker push ${{ secrets.DOCKER_USER }}/capsule-api
