---
api:
  host: api.domain.tld
  app_name: 'capsule-api'
  debug: false
  sqlalchemy:
    echo: false
    track_modifications: false
  secret_key: 'somesecretormaybenot'
  admins:
    - admin_user
  superadmins:
    - superadmin_user
  oidc:
    client_secrets:
      web:
        issuer: "https://myopenid-server.domain.tld/auth/realms/my-realm"
        auth_uri: "https://myopenid-server.domain.tld/auth/realms/my-realm/protocol/openid-connect/auth"
        client_id: "api-my-client-id"
        client_secret: "ffffffff-ffff-ffff-ffff-ffffffffffff"
        redirect_uris:
          - "http://localhost:5000/*"
        userinfo_uri: "https://myopenid-server.domain.tld/auth/realms/my-realm/protocol/openid-connect/userinfo"
        token_uri: "https://myopenid-server.domain.tld/auth/realms/my-realm/protocol/openid-connect/token"
        token_introspection_uri: "https://myopenid-server.domain.tld/auth/realms/my-realm/protocol/openid-connect/token/introspect"
        admin_uri: "https://myopenid-server.domain.tld/auth/admin/realms/my-realm"
    id_token_cookie_secure: false
    require_verified_email: false
    user_info_enabled: true
    openid_realm: 'flask-demo'
    scopes: ['openid', 'email', 'profile']
    introspection_auth_method: 'client_secret_post'
  env: 'development'
  database_uri: 'sqlite:///test_capsule.db'
  nats:
    uri: 'nats://localhost:4222'
    log_level: 'WARN'
    ca_cert: null
  rsa_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    unused for tests
    -----END RSA PRIVATE KEY-----
  # rsa_public_key: |
  #   -----BEGIN PUBLIC KEY-----
  #   unused for tests
  #   -----END PUBLIC KEY-----

drivers:
  k8s: # in the "from" key of a NATS message.
    rsa_public_key: |
      -----BEGIN PUBLIC KEY-----
      unused for tests
      -----END PUBLIC KEY-----
