"""camelCase to snake_case

Revision ID: 015035db7ede
Revises: c3c7356e0cab
Create Date: 2020-05-15 15:01:05.924459

"""
from alembic import op
import sqlalchemy as sa
import models
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '015035db7ede'
down_revision = 'c3c7356e0cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('available_options', sa.Column('field_description', sa.String(length=256), nullable=True))
    op.add_column('available_options', sa.Column('field_name', sa.String(length=256), nullable=False))
    op.drop_column('available_options', 'name')
    op.drop_column('available_options', 'description')
    op.add_column('runtimes', sa.Column('runtime_type', sa.Enum('webapp', 'addon', name='runtimetypeenum'), nullable=False))
    op.drop_column('runtimes', 'runtimeType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runtimes', sa.Column('runtimeType', mysql.ENUM('webapp', 'addon'), nullable=False))
    op.drop_column('runtimes', 'runtime_type')
    op.add_column('available_options', sa.Column('description', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('available_options', sa.Column('name', mysql.VARCHAR(length=256), nullable=False))
    op.drop_column('available_options', 'field_name')
    op.drop_column('available_options', 'field_description')
    # ### end Alembic commands ###
