"""Add cron to webapp

Revision ID: 04aa2c1d4849
Revises: b0e95dfa09d7
Create Date: 2020-06-17 09:21:54.231780

"""
from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision = '04aa2c1d4849'
down_revision = 'b0e95dfa09d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webapps', sa.Column('cron_cmd', sa.String(length=256), nullable=True))
    op.add_column('webapps', sa.Column('cron_schedule', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webapps', 'cron_schedule')
    op.drop_column('webapps', 'cron_cmd')
    # ### end Alembic commands ###
