"""add acme_certificate

Revision ID: 0a14fadf7be6
Revises: 1caab1a313d6
Create Date: 2021-06-23 15:21:10.503766

"""
from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision = '0a14fadf7be6'
down_revision = '1caab1a313d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capsules', sa.Column('acme_certificate', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capsules', 'acme_certificate')
    # ### end Alembic commands ###
