"""no_update become date

Revision ID: 1121a6f0c8de
Revises: a0141c36b7c0
Create Date: 2021-03-05 11:48:49.709201

"""
from alembic import op
import sqlalchemy as sa
import models
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1121a6f0c8de'
down_revision = 'a0141c36b7c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('capsules', 'no_update',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.execute("UPDATE capsules SET no_update = '1970-01-01 10:00:00';")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('capsules', 'no_update',
               existing_type=sa.DateTime(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    # ### end Alembic commands ###
