"""capsule name unique

Revision ID: 15a391bbe8b8
Revises: 87bc886d7a3c
Create Date: 2020-05-13 15:10:29.731157

"""
from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision = '15a391bbe8b8'
down_revision = '87bc886d7a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'capsules', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'capsules', type_='unique')
    # ### end Alembic commands ###
