"""fqdn name is unique

Revision ID: 16810f949d1f
Revises: e12fbfee4bf4
Create Date: 2021-02-02 17:18:55.107490

"""
from alembic import op
import sqlalchemy as sa
import models
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16810f949d1f'
down_revision = 'e12fbfee4bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('capsules', 'tls_redirect_https',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.create_unique_constraint(None, 'fqdns', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fqdns', type_='unique')
    op.alter_column('capsules', 'tls_redirect_https',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###
