"""add addons_offset to capsule

Revision ID: 1caab1a313d6
Revises: 145a3fd851e3
Create Date: 2021-04-27 10:14:13.789439

"""
from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision = '1caab1a313d6'
down_revision = '145a3fd851e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capsules', sa.Column('addons_offset', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capsules', 'addons_offset')
    # ### end Alembic commands ###
