"""add crons

Revision ID: 228f27325d5e
Revises: b55976990c02
Create Date: 2020-07-07 11:51:22.693548

"""
from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision = '228f27325d5e'
down_revision = 'b55976990c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crons',
    sa.Column('id', models.GUID(), nullable=False),
    sa.Column('webapp_id', models.GUID(), nullable=True),
    sa.Column('command', sa.String(length=256), nullable=False),
    sa.Column('hour', sa.String(length=256), nullable=True),
    sa.Column('minute', sa.String(length=256), nullable=True),
    sa.Column('month', sa.String(length=256), nullable=True),
    sa.Column('month_day', sa.String(length=256), nullable=True),
    sa.Column('week_day', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['webapp_id'], ['webapps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crons')
    # ### end Alembic commands ###
