"""Change runtime type column name

Revision ID: 2298ab0574e7
Revises: 15a391bbe8b8
Create Date: 2020-05-15 11:51:34.782545

"""
from alembic import op
import sqlalchemy as sa
import models
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2298ab0574e7'
down_revision = '15a391bbe8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runtimes', sa.Column('runtimeType', sa.Enum('webapp', 'addon', name='runtimetypeenum'), nullable=False))
    op.drop_column('runtimes', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runtimes', sa.Column('type', mysql.ENUM('webapp', 'addon'), nullable=False))
    op.drop_column('runtimes', 'runtimeType')
    # ### end Alembic commands ###
