"""add value_type to opt

Revision ID: 47039cab374c
Revises: 2e953720b1bd
Create Date: 2020-11-16 17:50:48.904608

"""
from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision = '47039cab374c'
down_revision = '2e953720b1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('value_type', sa.Enum('integer', 'float', 'boolean', 'string', 'base64', name='optionvaluetypeenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('options', 'value_type')
    # ### end Alembic commands ###
