"""add delegate_webapp_admin to capsule

Revision ID: 4e0b088cdf8e
Revises: 8be9199174bf
Create Date: 2021-01-27 17:48:52.402126

"""
from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision = '4e0b088cdf8e'
down_revision = '8be9199174bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capsules', sa.Column('delegate_webapp_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capsules', 'delegate_webapp_admin')
    # ### end Alembic commands ###
