"""add users.parts_manager and capsules.size

Revision ID: 566cfbfc6342
Revises: 1121a6f0c8de
Create Date: 2021-03-17 16:00:18.532803

"""
from alembic import op
import sqlalchemy as sa
import models
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '566cfbfc6342'
down_revision = '1121a6f0c8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addons', 'quota_memory_max')
    op.drop_column('addons', 'quota_volume_size')
    op.drop_column('addons', 'quota_cpu_max')
    op.add_column('capsules', sa.Column('size', sa.Enum('tiny', 'small', 'medium', 'large', 'xlarge', name='sizeenum'), nullable=False))
    op.add_column('users', sa.Column('parts_manager', sa.Boolean(0), nullable=False))
    op.drop_column('webapps', 'quota_memory_max')
    op.drop_column('webapps', 'quota_volume_size')
    op.drop_column('webapps', 'quota_cpu_max')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webapps', sa.Column('quota_cpu_max', mysql.VARCHAR(collation='utf8_unicode_ci', length=256), nullable=True))
    op.add_column('webapps', sa.Column('quota_volume_size', mysql.VARCHAR(collation='utf8_unicode_ci', length=256), nullable=True))
    op.add_column('webapps', sa.Column('quota_memory_max', mysql.VARCHAR(collation='utf8_unicode_ci', length=256), nullable=True))
    op.drop_column('users', 'parts_manager')
    op.drop_column('capsules', 'size')
    op.add_column('addons', sa.Column('quota_cpu_max', mysql.VARCHAR(collation='utf8_unicode_ci', length=256), nullable=True))
    op.add_column('addons', sa.Column('quota_volume_size', mysql.VARCHAR(collation='utf8_unicode_ci', length=256), nullable=True))
    op.add_column('addons', sa.Column('quota_memory_max', mysql.VARCHAR(collation='utf8_unicode_ci', length=256), nullable=True))
    # ### end Alembic commands ###
