"""split tls_redirect_https

Revision ID: a0141c36b7c0
Revises: 16810f949d1f
Create Date: 2021-02-05 16:45:31.688813

"""
from alembic import op
import sqlalchemy as sa
import models
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0141c36b7c0'
down_revision = '16810f949d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capsules', sa.Column('enable_https', sa.Boolean(), nullable=True))
    op.execute("ALTER TABLE capsules CHANGE tls_redirect_https force_redirect_https TINYINT(1)")
    op.execute("UPDATE capsules SET enable_https = force_redirect_https")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE capsules CHANGE force_redirect_https tls_redirect_https TINYINT(1)")
    op.drop_column('capsules', 'enable_https')
    # ### end Alembic commands ###
