"""Option values are Text

Revision ID: a441515c9fd0
Revises: c54b9cf1ced1
Create Date: 2020-08-27 12:27:13.744004

"""
from alembic import op
import sqlalchemy as sa
import models
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a441515c9fd0'
down_revision = 'c54b9cf1ced1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('available_options', 'default_value',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('options', 'value',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('options', 'value',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('available_options', 'default_value',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###
