"""Add uri_template to runtime

Revision ID: b55976990c02
Revises: b0e95dfa09d7
Create Date: 2020-06-19 15:35:14.768216

"""
from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision = 'b55976990c02'
down_revision = 'b0e95dfa09d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runtimes', sa.Column('uri_template', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runtimes', 'uri_template')
    # ### end Alembic commands ###
