"""Change key from spec

Revision ID: bb745e812153
Revises: 2298ab0574e7
Create Date: 2020-05-15 12:09:44.313107

"""
from alembic import op
import sqlalchemy as sa
import models
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb745e812153'
down_revision = '2298ab0574e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runtimes', sa.Column('desc', sa.String(length=256), nullable=True))
    op.add_column('runtimes', sa.Column('fam', sa.String(length=256), nullable=True))
    op.drop_column('runtimes', 'description')
    op.drop_column('runtimes', 'family')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runtimes', sa.Column('family', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('runtimes', sa.Column('description', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('runtimes', 'fam')
    op.drop_column('runtimes', 'desc')
    # ### end Alembic commands ###
