"""Fix Runtime nullables

Revision ID: c3c7356e0cab
Revises: bb745e812153
Create Date: 2020-05-15 13:51:41.868561

"""
from alembic import op
import sqlalchemy as sa
import models
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3c7356e0cab'
down_revision = 'bb745e812153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runtimes', 'desc',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('runtimes', 'fam',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runtimes', 'fam',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('runtimes', 'desc',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###
