"""typo in runtime column

Revision ID: c54b9cf1ced1
Revises: 228f27325d5e
Create Date: 2020-08-17 14:29:37.396080

"""
from alembic import op
import sqlalchemy as sa
import models
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c54b9cf1ced1'
down_revision = '228f27325d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runtimes', 'desc', nullable=False, existing_type=mysql.VARCHAR(length=256), new_column_name='description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runtimes', 'description', nullable=False, existing_type=mysql.VARCHAR(length=256), new_column_name='desc')
    # ### end Alembic commands ###
