"""add app token

Revision ID: c893ec7b7475
Revises: 7c0052a9ca81
Create Date: 2020-06-04 14:26:23.992300

"""
from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision = 'c893ec7b7475'
down_revision = '7c0052a9ca81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apptokens',
    sa.Column('id', models.GUID(), nullable=False),
    sa.Column('app', sa.String(length=256), nullable=False),
    sa.Column('owner_id', models.GUID(), nullable=True),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apptokens')
    # ### end Alembic commands ###
