"""Add uid to webapp

Revision ID: dde4dddc652b
Revises: e6092d695b3d
Create Date: 2020-06-12 17:11:30.499438

"""
from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision = 'dde4dddc652b'
down_revision = 'e6092d695b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webapps', sa.Column('uid', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'webapps', ['uid'])
    op.execute("ALTER TABLE webapps MODIFY uid INTEGER NOT NULL AUTO_INCREMENT")
    op.execute("ALTER TABLE webapps AUTO_INCREMENT = 5001")

    # Autoincrement
    # Non nullable
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'webapps', type_='unique')
    op.drop_column('webapps', 'uid')
    # ### end Alembic commands ###
