"""cert are Text

Revision ID: eda798970d46
Revises: 3dcfe0af20a5
Create Date: 2020-05-28 17:21:45.916037

"""
from alembic import op
import sqlalchemy as sa
import models
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eda798970d46'
down_revision = '3dcfe0af20a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webapps', 'tls_crt',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('webapps', 'tls_key',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webapps', 'tls_key',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('webapps', 'tls_crt',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###
