# TODO: Fill metadata correctly (info key, servers, etc.)
openapi: "3.0.2"

info:
  title: Capsule API
  version: "1.0"
  description: Web Platform Management API
  contact:
    name: API Support
    email: support@example.com
    url: http://example.com/support
  termsOfService: http://example.com/terms/
  license:
    name: GNU GPLv3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html

servers:
  - url: 'https://{platform}.api.example.com/v1'
    variables:
      platform:
        enum:
          - elea
          - dane
        default: elea

components:
  securitySchemes:
    $ref: ./components/securitySchemes.yaml
  parameters:
    $ref: ./components/parameters.yaml
  requestBodies: {}
  responses:
    $ref: ./components/responses.yaml
  schemas:
    $ref: ./components/schemas.yaml

paths:
  /users:
    $ref: ./paths/users.yaml
  /users/{user_id}:
    $ref: ./paths/user-by-id.yaml

  /capsules:
    $ref: ./paths/capsules.yaml
  /capsules/{capsule_id}:
    $ref: ./paths/capsule-by-id.yaml
  /capsules/{capsule_id}/owners:
    $ref: ./paths/capsule/owners.yaml
  /capsules/{capsule_id}/owners/{user_id}:
    $ref: ./paths/capsule/owner-by-id.yaml
  /capsules/{capsule_id}/webapp:
    $ref: ./paths/capsule/webapp.yaml
  /capsules/{capsule_id}/addons:
    $ref: ./paths/capsule/addons.yaml
  /capsules/{capsule_id}/addons/{addon_id}:
    $ref: ./paths/capsule/addon-by-id.yaml

  /runtimes:
    $ref: ./paths/runtimes.yaml
  /runtimes/{runtime_id}:
    $ref: ./paths/runtime-by-id.yaml

  # Self endpoints
  /sshkeys:
    $ref: ./paths/sshkeys.yaml
  /sshkeys/{sshkey_id}:
    $ref: ./paths/sshkey-by-id.yaml