openapi: "3.0.2"

info:
  title: Capsule API
  version: "__API_VERSION__"
  description: __PLATFORM_DESCRIPTION__
  contact:
    name: Académie de Versailles
    url: http://www.ac-versailles.fr/pid35231/nous-contacter.html
  license:
    name: GNU GPLv3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html

servers:
  - url: 'https://console.__PLATFORM__.paas.in.ac-versailles.fr/v2'

components:
  securitySchemes:
    $ref: ./components/securitySchemes.yaml
  parameters:
    $ref: ./components/parameters.yaml
  requestBodies: {}
  responses:
    $ref: ./components/responses.yaml
  schemas:
    $ref: ./components/schemas.yaml

paths:
  /users:
    $ref: ./paths/users.yaml
  /users/{user_id}:
    $ref: ./paths/user-by-id.yaml

  /capsules:
    $ref: ./paths/capsules.yaml
  /capsules/{capsule_id}:
    $ref: ./paths/capsule-by-id.yaml
  /capsules/{capsule_id}/owners:
    $ref: ./paths/capsule/owners.yaml
  /capsules/{capsule_id}/owners/{user_id}:
    $ref: ./paths/capsule/owner-by-id.yaml
  /capsules/{capsule_id}/webapp:
    $ref: ./paths/capsule/webapp.yaml
  /capsules/{capsule_id}/webapp/crons:
    $ref: ./paths/capsule/webapp/crons.yaml
  /capsules/{capsule_id}/webapp/crons/{cron_id}:
    $ref: ./paths/capsule/webapp/cron-by-id.yaml
  /capsules/{capsule_id}/addons:
    $ref: ./paths/capsule/addons.yaml
  /capsules/{capsule_id}/addons/{addon_id}:
    $ref: ./paths/capsule/addon-by-id.yaml
  /capsules/{capsule_id}/sshkeys:
    $ref: ./paths/capsule/sshkeys.yaml
  /capsules/{capsule_id}/sshkeys/{sshkey_id}:
    $ref: ./paths/capsule/sshkey-by-id.yaml
  /capsules/{capsule_id}/fqdns:
    $ref: ./paths/capsule/fqdns.yaml
  /capsules/{capsule_id}/fqdns/{fqdn_id}:
    $ref: ./paths/capsule/fqdn-by-id.yaml
  /capsules/{capsule_id}/tls:
    $ref: ./paths/capsule/tls.yaml
  /capsules/{capsule_id}/delegate:
    $ref: ./paths/capsule/delegate.yaml

  /runtimes:
    $ref: ./paths/runtimes.yaml
  /runtimes/{runtime_id}:
    $ref: ./paths/runtime-by-id.yaml

  /sshkeys:
    $ref: ./paths/sshkeys.yaml
  /sshkeys/{sshkey_id}:
    $ref: ./paths/sshkey-by-id.yaml

  /apptokens:
    $ref: ./paths/app-tokens.yaml
  /apptokens/{apptoken_id}:
    $ref: ./paths/app-token-by-id.yaml

  /me:
    $ref: ./paths/me.yaml

  /cluster:
    $ref: ./paths/cluster.yaml