offset:
  in: query
  name: offset
  description: The number of items to skip before collecting the result set
  required: false
  schema:
    type: integer
    minimum: 0
    default: 0
limit:
  in: query
  name: limit
  description: The number of items to return
  required: false
  schema:
    type: integer
    minimum: 1
    maximum: 100
    default: 20
verbose:
  in: query
  name: verbose
  description: Whether the response much display additional information about the requested resource
  required: false
  schema:
    type: boolean
    default: false
filters:
  in: query
  name: filters
  description: The fields of the response to filter by
  required: false
  schema:
    type: object
    default: {}
  style: form
  explode: true

capsule_id:
  in: path
  name: capsule_id
  required: true
  description: Capsule GUID
  schema:
    type: string
addon_id:
  in: path
  name: addon_id
  required: true
  description: AddOn GUID
  schema:
    type: string
runtime_id:
  in: path
  name: runtime_id
  required: true
  description: Runtime GUID
  schema:
    type: string
user_id:
  in: path
  name: user_id
  required: true
  description: User LDAP nsUniqueId
  schema:
    type: string
sshkey_id:
  in: path
  name: sshkey_id
  required: true
  description: SSH Key GUID
  schema:
    type: string